[notebook]
dir = "~/Documents/Notes"

[note]
# Language used when writing notes.
# This is used to generate slugs or with date formats.
language = "en"

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}"

# The file extension used for the notes.
extension = "md"

# Configure random ID generation.
# The charset used for random IDs.
id-charset = "alphanum"

# Length of the generated IDs.
id-length = 8

# Letter case for the random IDs.
id-case = "lower"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

[extra]
author = "Yannick D."

[group.daily]
paths = ["journal"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[group.moc]
paths = ["moc"]

[group.moc.note]
filename = "{{slug title}}"
extension = "md"

[format.markdown]
# Enable support for #hashtags
hashtags = true
# Enable support for :colon:separated:tags:
colon-tags = true

[tool]
# Default editor used to open notes.
editor = "nvim"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]
# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $argv"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# List notes for editing
ls = "zk edit --interactive"

# Search notes by tags
tags = "zk edit --interactive --tag $argv"

config = 'nvim "$HOME/.config/zk/config.toml"'

# New daily entry
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal"'

# Create new note
nt = 'zk new --title "$*"'

# Browse daily notes
journal = "zk edit --sort created- $ZK_NOTEBOOK_DIR/journal --interactive"

# Remove a files
rm = "zk list --interactive --quiet --format path --delimiter0 $argv | xargs -0 rm -vf --"

# Create Map of Content note
moc = 'zk new --no-input "$ZK_NOTEBOOK_DIR/moc" --title "$*"'

[lsp]
[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
