blacklist = ["scratch"]

[default_session]
preview_command = "eza --long --header --icons --all --group-directories-first --git --color=always {}"

[[session]]
name = "home"
path = "~"

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "downloads"
path = "~/Downloads"
# path = "~/Téléchargements"

[[session]]
name = "tmux config"
path = "~/dotfiles/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/dotfiles/tmux/tmux.conf"

[[session]]
name = "neovim config"
path = "~/dotfiles/neovims/LazyVim"
startup_command = "nvim"

[[session]]
name = "sesh config"
path = "~/dotfiles/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/dotfiles/sesh/sesh.toml"

[[session]]
name = "yazi config"
path = "~/dotfiles/yazi"
startup_command = "nvim yazi.toml"
preview_command = "bat --color=always ~/dotfiles/yazi/yazi.toml"

[[session]]
name = "hyprland config"
path = "~/dotfiles/hypr"
startup_command = "nvim"

[[session]]
name = "fish config"
path = "~/dotfiles/fish"
startup_command = "nvim"
preview_command = "bat --color=always ~/dotfiles/fish/config.fish"

[[session]]
name = "ghostty config"
path = "~/dotfiles/ghostty"
startup_command = "nvim config"

[[session]]
name = "Freelancing"
path = "~/Work/Freelance"
